export const urlPage = {
  HOME: '/',
  PRODUCT: '/product',
  GUEST: '/guest',
  LOGIN: '/guest/login',
  REGISTER_USER: '/guest/register',
  PROFILE: '/profile',
  CART: '/cart',
  SHIPMENT: '/cart/shipment',
  USER: '/user',
  USER_SETTING: '/user/settings',
  USER_ADDRESS: '/user/settings/address',
  MY_SHOP: '/myshop',
  WISHLIST: '/wishlist',
  TRANSACTION: '/order-list',
  SELLER: '/seller',
  SELLER_HOME: '/seller/home',
  SELLER_PRODUCT: '/seller/product',
  SELLER_SETTING: '/seller/settings',
  SELLER_SETTING_INFO: '/seller/settings/info',
  SELLER_SETTING_OPERATIONAL: '/seller/settings/operational-hour',
  SELLER_SETTING_ADDRESS: '/seller/settings/address',
}
