import {
  AnFilledInstagram,
  AnFilledSetting,
  BsFacebook,
  CaPlayOutlineFilled,
  FaBandsSquareTwitter,
  FlFilledClipboardText,
  HiSolidHome,
  PhFillPackage,
} from '@kalimahapps/vue-icons'
import { ref } from 'vue'
import type { Product, Slide } from './interface'
import { urlPage } from './constans'

export const listImg = [
  {
    img: 'https://via.placeholder.com/200x300?text=Free',
    desc: 'Buka toko gratis tanpa biaya apapun',
  },
  {
    img: 'https://via.placeholder.com/200x300?text=90 Juta',
    desc: 'Lebih dari 90 juta pengguna aktif setiap bulan',
  },
  {
    img: 'https://via.placeholder.com/200x300?text=Map',
    desc: 'Menjangkau pembeli potensial di 97% di wilayah indonesia',
  },
]

export const slides = ref<Slide[]>([
  {
    image:
      'https://images.tokopedia.net/img/cache/1208/NsjrJu/2024/10/22/85a37f44-1d7e-492d-b241-88b9b13a925d.jpg.webp?ect=4g',
    title: 'Welcome to Our Site',
    description: 'Discover amazing things with us!',
  },
  {
    image:
      'https://images.tokopedia.net/img/cache/1208/NsjrJu/2024/10/24/85a25bb5-3865-46d6-99b2-e5b700c6a0e0.jpg.webp?ect=4g',
    title: 'Our Services',
    description: 'We provide the best solutions for you.',
  },
  {
    image:
      'https://images.tokopedia.net/img/cache/1208/NsjrJu/2024/10/24/18189109-4504-46ed-b9d0-2443cc3cff89.jpg.webp?ect=4g',
    title: 'Join Us Today',
    description: 'Be a part of our community.',
  },
])

export const dataProduct = [
  {
    id: '1',
    product_name: 'Ellipsesinc - Kaos Oversize Pria Wanita NY',
    color: 'putih',
    price: 'Rp43.900',
    address: 'Jakarta Barat',
    rating: '4.2',
    count_sales: '400',
    merchant_name: 'jakaslot',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+1',
    createdAt: '2024-11-01T08:30:00Z',
  },
  {
    id: '2',
    product_name: 'Celana Chino Slim Fit',
    color: 'hitam',
    price: 'Rp125.000',
    address: 'Bandung',
    rating: '4.5',
    count_sales: '250',
    merchant_name: 'fashion_hub',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+2',
    createdAt: '2024-10-28T10:15:00Z',
  },
  {
    id: '3',
    product_name: 'Sepatu Lari Olahraga',
    color: 'abu-abu',
    price: 'Rp430.000',
    address: 'Surabaya',
    rating: '4.8',
    count_sales: '320',
    merchant_name: 'sporty_shoes',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+3',
    createdAt: '2024-10-20T14:45:00Z',
  },
  {
    id: '4',
    product_name: 'Jam Tangan Smartwatch',
    color: 'biru',
    price: 'Rp1.500.000',
    address: 'Jakarta Selatan',
    rating: '4.9',
    count_sales: '500',
    merchant_name: 'tech_guru',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+4',
    createdAt: '2024-11-15T12:00:00Z',
  },
  {
    id: '5',
    product_name: 'Tas Ransel Anti Air',
    color: 'hijau',
    price: 'Rp240.000',
    address: 'Malang',
    rating: '4.7',
    count_sales: '100',
    merchant_name: 'outdoor_gears',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+5',
    createdAt: '2024-10-05T16:30:00Z',
  },
  {
    id: '6',
    product_name: 'Kemeja Kasual Polos',
    color: 'biru tua',
    price: 'Rp150.000',
    address: 'Yogyakarta',
    rating: '4.4',
    count_sales: '75',
    merchant_name: 'classic_wear',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+6',
    createdAt: '2024-09-25T09:20:00Z',
  },
  {
    id: '7',
    product_name: 'Headset Gaming RGB',
    color: 'hitam',
    price: 'Rp750.000',
    address: 'Tangerang',
    rating: '4.6',
    count_sales: '300',
    merchant_name: 'gaming_corner',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+7',
    createdAt: '2024-11-10T11:00:00Z',
  },
  {
    id: '8',
    product_name: 'Botol Minum Stainless Steel',
    color: 'silver',
    price: 'Rp89.000',
    address: 'Denpasar',
    rating: '4.3',
    count_sales: '150',
    merchant_name: 'drink_smart',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+8',
    createdAt: '2024-10-15T13:45:00Z',
  },
  {
    id: '9',
    product_name: 'Set Pisau Dapur Premium',
    color: 'hitam',
    price: 'Rp650.000',
    address: 'Medan',
    rating: '4.8',
    count_sales: '90',
    merchant_name: 'kitchen_tools',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+9',
    createdAt: '2024-09-18T10:00:00Z',
  },
  {
    id: '10',
    product_name: 'Lampu Meja Belajar LED',
    color: 'putih',
    price: 'Rp180.000',
    address: 'Palembang',
    rating: '4.5',
    count_sales: '200',
    merchant_name: 'study_light',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+10',
    createdAt: '2024-11-12T08:00:00Z',
  },
  {
    id: '11',
    product_name: 'Topi Snapback Streetwear',
    color: 'hitam',
    price: 'Rp95.000',
    address: 'Makassar',
    rating: '4.2',
    count_sales: '180',
    merchant_name: 'urban_headgear',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+11',
    createdAt: '2024-10-22T14:30:00Z',
  },
  {
    id: '12',
    product_name: 'Powerbank 20.000 mAh',
    color: 'putih',
    price: 'Rp350.000',
    address: 'Bandung',
    rating: '4.7',
    count_sales: '320',
    merchant_name: 'charge_master',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+12',
    createdAt: '2024-11-01T12:15:00Z',
  },
  {
    id: '13',
    product_name: 'Rak Buku Minimalis',
    color: 'coklat',
    price: 'Rp425.000',
    address: 'Semarang',
    rating: '4.6',
    count_sales: '150',
    merchant_name: 'furniture_home',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+13',
    createdAt: '2024-09-27T16:45:00Z',
  },
  {
    id: '14',
    product_name: 'Set Alat Makan Keramik',
    color: 'putih',
    price: 'Rp550.000',
    address: 'Jakarta Timur',
    rating: '4.8',
    count_sales: '275',
    merchant_name: 'elegant_dining',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+14',
    createdAt: '2024-10-18T10:30:00Z',
  },
  {
    id: '15',
    product_name: 'Mouse Gaming Wireless',
    color: 'merah',
    price: 'Rp299.000',
    address: 'Depok',
    rating: '4.3',
    count_sales: '200',
    merchant_name: 'tech_zone',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+15',
    createdAt: '2024-11-03T09:45:00Z',
  },
  {
    id: '16',
    product_name: 'Kamera Mirrorless 24MP',
    color: 'hitam',
    price: 'Rp6.750.000',
    address: 'Surabaya',
    rating: '4.9',
    count_sales: '500',
    merchant_name: 'capture_pro',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+16',
    createdAt: '2024-10-07T11:30:00Z',
  },
  {
    id: '17',
    product_name: 'Casing Handphone Anti Guncangan',
    color: 'transparan',
    price: 'Rp85.000',
    address: 'Tangerang',
    rating: '4.2',
    count_sales: '300',
    merchant_name: 'phone_guard',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+17',
    createdAt: '2024-11-05T13:00:00Z',
  },
  {
    id: '18',
    product_name: 'Kipas Angin Portable',
    color: 'pink',
    price: 'Rp150.000',
    address: 'Denpasar',
    rating: '4.4',
    count_sales: '180',
    merchant_name: 'cool_breeze',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+18',
    createdAt: '2024-10-15T08:15:00Z',
  },
  {
    id: '19',
    product_name: 'Cokelat Premium Hampers',
    color: 'coklat tua',
    price: 'Rp450.000',
    address: 'Yogyakarta',
    rating: '4.5',
    count_sales: '120',
    merchant_name: 'sweet_gifts',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+19',
    createdAt: '2024-09-28T15:45:00Z',
  },
  {
    id: '20',
    product_name: 'Celana Legging Olahraga',
    color: 'hitam',
    price: 'Rp120.000',
    address: 'Medan',
    rating: '4.1',
    count_sales: '300',
    merchant_name: 'status_wear',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+20',
    createdAt: '2024-11-08T07:30:00Z',
  },
  {
    id: '21',
    product_name: 'Tenda Camping Outdoor',
    color: 'hijau',
    price: 'Rp1.200.000',
    address: 'Malang',
    rating: '4.7',
    count_sales: '220',
    merchant_name: 'outdoor_life',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+21',
    createdAt: '2024-09-20T11:20:00Z',
  },
  {
    id: '22',
    product_name: 'Lemari Pakaian Portable',
    color: 'biru muda',
    price: 'Rp800.000',
    address: 'Palembang',
    rating: '4.5',
    count_sales: '310',
    merchant_name: 'home_essentials',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+22',
    createdAt: '2024-10-25T09:45:00Z',
  },
  {
    id: '23',
    product_name: 'Set Makeup Profesional',
    color: 'pink',
    price: 'Rp1.500.000',
    address: 'Makassar',
    rating: '4.8',
    count_sales: '150',
    merchant_name: 'beauty_kit',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+23',
    createdAt: '2024-11-09T12:00:00Z',
  },
  {
    id: '24',
    product_name: 'Sepatu Kulit Formal',
    color: 'coklat tua',
    price: 'Rp950.000',
    address: 'Jakarta Barat',
    rating: '4.9',
    count_sales: '500',
    merchant_name: 'formal_footwear',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+24',
    createdAt: '2024-11-14T10:00:00Z',
  },
  {
    id: '25',
    product_name: 'Gelang Fitness Tracker',
    color: 'hitam',
    price: 'Rp450.000',
    address: 'Bandung',
    rating: '4.6',
    count_sales: '320',
    merchant_name: 'fit_tech',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+25',
    createdAt: '2024-10-12T14:15:00Z',
  },
  {
    id: '26',
    product_name: 'Timbangan Badan Digital',
    color: 'putih',
    price: 'Rp275.000',
    address: 'Jakarta Selatan',
    rating: '4.5',
    count_sales: '180',
    merchant_name: 'health_tools',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+26',
    createdAt: '2024-09-30T08:00:00Z',
  },
  {
    id: '27',
    product_name: 'Set Sprei dan Sarung Bantal',
    color: 'biru',
    price: 'Rp380.000',
    address: 'Surabaya',
    rating: '4.4',
    count_sales: '200',
    merchant_name: 'home_comfort',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+27',
    createdAt: '2024-11-13T10:30:00Z',
  },
  {
    id: '28',
    product_name: 'Mesin Kopi Espresso',
    color: 'silver',
    price: 'Rp2.300.000',
    address: 'Jakarta Utara',
    rating: '4.9',
    count_sales: '250',
    merchant_name: 'coffee_brew',
    poster_path: 'https://via.placeholder.com/200x300?text=Product+28',
    createdAt: '2024-10-08T11:15:00Z',
  },
]

export const navItems = [
  {
    name: 'home',
    label: 'Home',
    route: urlPage.SELLER_HOME,
    icon: HiSolidHome,
    size: 'h-7 w-7',
  },
  {
    name: 'produk',
    label: 'Produk',
    route: urlPage.SELLER_PRODUCT,
    icon: PhFillPackage,
    size: 'h-7 w-7',
  },
  {
    name: 'pesanan',
    label: 'Pesanan',
    route: '#',
    icon: FlFilledClipboardText,
    size: 'h-7 w-7',
  },
  {
    name: 'pengaturan',
    label: 'Pengaturan',
    route: urlPage.SELLER_SETTING,
    icon: AnFilledSetting,
    size: 'h-7 w-7',
  },
]

export const links = [
  'Tentang Warder',
  'Hak Kekayaan Intelektual',
  'Karir',
  'Blog',
  'Beli Lokal',
  'Promo Hari Ini',
  'Promo Guncang',
  'Afiliate program',
  'Marketing Solution',
]

export const beliLink = ['Tagihan Dan Top Up', 'Warder COD', 'Bebas Ongkir']

export const jualLink = ['Pusat Edukasi Seller', 'Daftar Official Store']

export const bantuan = [
  'Warder Care',
  'Syarat Dan Ketentuan',
  'Kebijakan Privasi',
]

export const linkApps = [
  'https://assets.tokopedia.net/asts/assets-unify/img/icon-download-android.svg',
  'https://assets.tokopedia.net/asts/assets-unify/img/icon-download-ios.svg',
  'https://assets.tokopedia.net/asts/assets-unify/img/icon-download-huawei.svg',
]

export const linkSocmed = [
  { component: BsFacebook, sizeClass: 'w-7 h-7' },
  { component: FaBandsSquareTwitter, sizeClass: 'w-7 h-7' },
  { component: AnFilledInstagram, sizeClass: 'w-8 h-8' },
  { component: CaPlayOutlineFilled, sizeClass: 'w-8 h-8' },
]

export const products: Product[] = [
  {
    id: 1,
    name: 'Headset Earphone Samsung M23 M31 M33 Original 100% Super Bass',
    color: 'Putih',
    price: 'Rp35.500',
    image:
      'https://images.tokopedia.net/img/cache/100-square/VqbcmM/2023/5/29/93db4e43-41a2-4d4f-bbf4-b45dbf34cfce.jpg',
  },
  {
    id: 2,
    name: 'Earphone JBL T110 In-Ear',
    color: 'Hitam',
    price: 'Rp150.000',
    image: 'https://via.placeholder.com/80x80?text=Product+1',
  },
  {
    id: 3,
    name: 'Sony WH-CH510 Wireless Headphone',
    color: 'Biru',
    price: 'Rp550.000',
    image: 'https://via.placeholder.com/80x80?text=Product+2',
  },
  {
    id: 4,
    name: 'Xiaomi Redmi AirDots',
    color: 'Merah',
    price: 'Rp120.000',
    image: 'https://via.placeholder.com/80x80?text=Product+3',
  },
  {
    id: 5,
    name: 'Samsung Galaxy Buds Live',
    color: 'Emerald',
    price: 'Rp1.200.000',
    image: 'https://via.placeholder.com/80x80?text=Product+4',
  },
]

export const listCost = [
  'Total Harga',
  'Total Ongkos Kirim',
  'Biaya Jasa Aplikasi',
]

export const dataIdentity = [
  {
    label: 'Name',
    value: 'Tatang Haetami',
    type: 'personal',
  },
  {
    label: 'Tanggal Lahir',
    value: '11 September 2010',
    type: 'personal',
  },
  {
    label: 'Jenis Kelamin',
    value: 'Pria',
    type: 'personal',
  },
  {
    label: 'Email',
    value: 'tami@ganteng.com',
    type: 'contact',
  },
  {
    label: 'Nomor HP',
    value: '082260283276',
    type: 'contact',
  },
]

export const dataAddress = [
  {
    id: 1,
    label: 'Rumah',
    name: 'Tatang Haetami',
    phone: '082260283276',
    address:
      'Jln. Veteran, RT/RW : 02/03, Gambir, Kecamatan Gambir Jakarta pusat, DKI Jakarta',
    selected: true,
  },
  {
    id: 2,
    label: 'Kantor',
    name: 'Tatang Haetami',
    phone: '082260283277',
    address: 'Jl. Sudirman, Kav 50, Jakarta Selatan, DKI Jakarta',
    selected: false,
  },
  {
    id: 3,
    label: 'Apartemen',
    name: 'Tatang Haetami',
    phone: '082260283278',
    address: 'Jl. Casablanca, Kuningan, Jakarta Selatan, DKI Jakarta',
    selected: false,
  },
  {
    id: 4,
    label: 'Rumah Kedua',
    name: 'Tatang Haetami',
    phone: '082260283279',
    address: 'Jl. Palmerah, Kebayoran Lama, Jakarta Barat, DKI Jakarta',
    selected: false,
  },
  {
    id: 5,
    label: 'Rumah Ketiga',
    name: 'Tatang Haetami',
    phone: '082260283280',
    address: 'Jl. Thamrin, Jakarta Pusat, DKI Jakarta',
    selected: false,
  },
]

export const dataReviews = [
  {
    id: '1',
    customer: 'Yoona',
    image:
      'https://images.tokopedia.net/img/cache/100-square/default_v3-usrnophoto.png.webp?ect=4g',
    content: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit',
    rating: 3,
    createdAt: '1 hari lalu',
    replies: [
      {
        title: 'Balasan',
        content:
          'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur similique labore suscipit ipsam harum, delectus doloremque, placeat, animi ea recusandae consectetur aliqui praesentium eos corrupti hic molestias excepturi nostrum sequi.',
        value: '0',
        image:
          'https://images.tokopedia.net/img/cache/100-square/default_v3-usrnophoto.png.webp?ect=4g',
        shopName: 'Advance Digital Store',
        createdAt: '2 Jam lalu',
      },
    ],
  },
  {
    id: '2',
    customer: 'Rama',
    image:
      'https://images.tokopedia.net/img/cache/100-square/default_v3-usrnophoto.png.webp?ect=4g',
    content:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur similique labore suscipit ipsam harum, delectus doloremque, placeat,',
    rating: 5,
    createdAt: '4 hari lalu',
    replies: [
      {
        title: 'Balasan',
        content:
          'Lorem delectus doloremque, placeat, animi ea recusandae consectetur aliqui praesentium eos corrupti hic molestias excepturi nostrum sequi.',
        value: '0',
        image:
          'https://images.tokopedia.net/img/cache/100-square/default_v3-usrnophoto.png.webp?ect=4g',
        shopName: 'Advance Digital Store',
        createdAt: '2 Jam lalu',
      },
    ],
  },
]

export const dataTransactions = [
  {
    dateOrder: '7 Nov 2024',
    status: 'berhasil',
    invoice: 'INV/20231107/MPL/3552677877',
    shopName: 'Tanto Komputer',
    productImg: 'https://via.placeholder.com/80x80?text=Product+1',
    productName: 'Earphone JBL T110 In-Ear',
    qty: '1',
    price: 'Rp20.000',
    totalPayment: 'Rp30.500',
  },
  {
    dateOrder: '6 Nov 2024',
    status: 'tidak berhasil',
    invoice: 'INV/20231106/MPL/3552677890',
    shopName: 'Dunia Elektronik',
    productImg: 'https://via.placeholder.com/80x80?text=Product+2',
    productName: 'Mouse Wireless Logitech',
    qty: '2',
    price: 'Rp50.000',
    totalPayment: 'Rp120.000',
  },
  {
    dateOrder: '5 Nov 2024',
    status: 'dibatalkan',
    invoice: 'INV/20231105/MPL/3552677900',
    shopName: 'Tech Corner',
    productImg: 'https://via.placeholder.com/80x80?text=Product+3',
    productName: 'Flashdisk Sandisk 32GB',
    qty: '1',
    price: 'Rp45.000',
    totalPayment: 'Rp50.000',
  },
  {
    dateOrder: '5 Nov 2024',
    status: 'berhasil',
    invoice: 'INV/20231105/MPL/3552677910',
    shopName: 'Gadget World',
    productImg: 'https://via.placeholder.com/80x80?text=Product+4',
    productName: 'Powerbank 10000mAh',
    qty: '1',
    price: 'Rp150.000',
    totalPayment: 'Rp155.000',
  },
  {
    dateOrder: '4 Nov 2024',
    status: 'tidak berhasil',
    invoice: 'INV/20231104/MPL/3552677920',
    shopName: 'Gaming Store',
    productImg: 'https://via.placeholder.com/80x80?text=Product+5',
    productName: 'Keyboard Mechanical RGB',
    qty: '1',
    price: 'Rp350.000',
    totalPayment: 'Rp360.000',
  },
  {
    dateOrder: '3 Nov 2024',
    status: 'dibatalkan',
    invoice: 'INV/20231103/MPL/3552677930',
    shopName: 'Alpha Tech',
    productImg: 'https://via.placeholder.com/80x80?text=Product+6',
    productName: 'Laptop Cooling Pad',
    qty: '1',
    price: 'Rp90.000',
    totalPayment: 'Rp100.000',
  },
  {
    dateOrder: '2 Nov 2024',
    status: 'berhasil',
    invoice: 'INV/20231102/MPL/3552677940',
    shopName: 'Mobile Accessories',
    productImg: 'https://via.placeholder.com/80x80?text=Product+7',
    productName: 'Charger Samsung Fast Charging',
    qty: '1',
    price: 'Rp80.000',
    totalPayment: 'Rp90.000',
  },
  {
    dateOrder: '1 Nov 2024',
    status: 'dibatalkan',
    invoice: 'INV/20231101/MPL/3552677950',
    shopName: 'Smart Gadgets',
    productImg: 'https://via.placeholder.com/80x80?text=Product+8',
    productName: 'Smartwatch Amazfit Bip',
    qty: '1',
    price: 'Rp600.000',
    totalPayment: 'Rp620.000',
  },
  {
    dateOrder: '31 Oct 2024',
    status: 'tidak berhasil',
    invoice: 'INV/20231031/MPL/3552677960',
    shopName: 'Tech Hub',
    productImg: 'https://via.placeholder.com/80x80?text=Product+9',
    productName: 'USB Hub 4 Port',
    qty: '1',
    price: 'Rp35.000',
    totalPayment: 'Rp40.000',
  },
  {
    dateOrder: '30 Oct 2024',
    status: 'berhasil',
    invoice: 'INV/20231030/MPL/3552677970',
    shopName: 'Office Supplies',
    productImg: 'https://via.placeholder.com/80x80?text=Product+10',
    productName: 'Printer Canon Pixma',
    qty: '1',
    price: 'Rp1.200.000',
    totalPayment: 'Rp1.250.000',
  },
]

export const statusData = [
  { name: 'Semua' },
  { name: 'Berlangsung' },
  { name: 'Berhasil' },
  { name: 'Tidak Berhasil' },
]

export const productPopular = [
  {
    image: 'https://via.placeholder.com/80x80?text=Product',
    name: 'Samsung Galaxy S23 Ultra',
    price: 'Rp.18,500,000',
  },
  {
    image: 'https://via.placeholder.com/80x80?text=Product+2',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    price: 'Rp.4,800,000',
  },
  {
    image: 'https://via.placeholder.com/80x80?text=Product',
    name: 'Apple MacBook Pro 14-inch M2',
    price: 'Rp.30,000,000',
  },
  {
    image: 'https://via.placeholder.com/80x80?text=Product',
    name: 'Nike Air Max 270 React',
    price: 'Rp.1,800,000',
  },
  {
    image: 'https://via.placeholder.com/80x80?text=Product',
    name: 'Oculus Quest 2 VR Headset',
    price: 'Rp.5,500,000',
  },
]

export const storeLocation = [
  {
    address:
      'Jln. Veteran, RT/RW : 02/03, Gambir, Kecamatan Gambir Jakarta pusat, DKI Jakarta',
    city: 'Gambir, Jakarta Pusat',
    postcode: '42000',
    status: true,
  },
]

export const dataArticle = [
  {
    title:
      'Dapatkan Teman Diskusi Berjualan dan Undangan Khusus Kegiatan SellerWarder',
    img: 'https://images.tokopedia.net/img/cache/350/kjjBfF/2024/11/15/2e5520d4-422d-4604-9ead-e2d61fa4c488.png.webp?ect=3g',
    category: 'Materi Seller Baru',
    createdAt: '15 Nov 2024',
  },
  {
    title: '[Pengiriman] Jenis-Jenis Pengiriman dan Cara Mengaturnya',
    img: 'https://images.tokopedia.net/img/cache/350/kjjBfF/2023/8/14/edd1da48-d8a3-4bf2-b03b-ec24e68239ac.jpg.webp?ect=3g',
    category: 'Materi Seller Baru',
    createdAt: '6 Nov 2024',
  },
  {
    title:
      'Selamat! Kamu Mendapatkan Voucher Menarik Hanya Dengan Menyelesaikan Tantangan Toko!🎉',
    img: 'https://images.tokopedia.net/img/cache/350/kjjBfF/2024/9/17/1809a313-9dff-40a9-b70e-e8d260c860b6.png.webp?ect=3g',
    category: 'Materi Seller Baru',
    createdAt: '3 Oct 2024',
  },
]

export const productSeller = [
  {
    name: 'Disney Tsum Tsum Squishies',
    img: 'https://via.placeholder.com/80x80?text=Product',
    price: '1000000',
    stock: 10,
    status: false,
    sku: 'A8900',
  },
  {
    name: 'LEGO Creator Expert Modular Buildings',
    img: 'https://via.placeholder.com/80x80?text=LEGO',
    price: '2500000',
    stock: 5,
    status: true,
    sku: 'L9201',
  },
  {
    name: 'Funko Pop! Marvel Spider-Man',
    img: 'https://via.placeholder.com/80x80?text=Funko+Pop',
    price: '350000',
    stock: 20,
    status: true,
    sku: 'F9800',
  },
  {
    name: 'Hot Wheels Monster Trucks',
    img: 'https://via.placeholder.com/80x80?text=Hot+Wheels',
    price: '150000',
    stock: 50,
    status: false,
    sku: 'HW7865',
  },
  {
    name: 'Barbie Dreamhouse Playset',
    img: 'https://via.placeholder.com/80x80?text=Barbie',
    price: '4500000',
    stock: 3,
    status: false,
    sku: 'BDR123',
  },
  {
    name: 'NERF Elite 2.0 Flipshots',
    img: 'https://via.placeholder.com/80x80?text=NERF',
    price: '400000',
    stock: 15,
    status: false,
    sku: 'NE2048',
  },
  {
    name: 'Play-Doh Kitchen Creations',
    img: 'https://via.placeholder.com/80x80?text=Play-Doh',
    price: '200000',
    stock: 30,
    status: true,
    sku: 'PD5934',
  },
  {
    name: 'Fisher-Price Laugh & Learn Puppy',
    img: 'https://via.placeholder.com/80x80?text=Fisher-Price',
    price: '500000',
    stock: 8,
    status: false,
    sku: 'FP3940',
  },
  {
    name: 'Transformers Optimus Prime Action Figure',
    img: 'https://via.placeholder.com/80x80?text=Transformers',
    price: '850000',
    stock: 12,
    status: false,
    sku: 'TF4098',
  },
  {
    name: 'Jenga Classic Game',
    img: 'https://via.placeholder.com/80x80?text=Jenga',
    price: '250000',
    stock: 25,
    status: true,
    sku: 'JG5623',
  },
  {
    name: 'Monopoly Classic Board Game',
    img: 'https://via.placeholder.com/80x80?text=Monopoly',
    price: '300000',
    stock: 18,
    status: true,
    sku: 'MP2023',
  },
  {
    name: 'Crayola Ultimate Crayon Collection',
    img: 'https://via.placeholder.com/80x80?text=Crayola',
    price: '450000',
    stock: 25,
    status: true,
    sku: 'CRY567',
  },
  {
    name: 'Baby Yoda Plush Toy',
    img: 'https://via.placeholder.com/80x80?text=Baby+Yoda',
    price: '750000',
    stock: 6,
    status: true,
    sku: 'BY1234',
  },
  {
    name: 'Paw Patrol Ultimate Rescue Fire Truck',
    img: 'https://via.placeholder.com/80x80?text=Paw+Patrol',
    price: '1200000',
    stock: 7,
    status: false,
    sku: 'PP8900',
  },
  {
    name: "Rubik's Cube 3x3",
    img: "https://via.placeholder.com/80x80?text=Rubik's+Cube",
    price: '100000',
    stock: 50,
    status: true,
    sku: 'RC333',
  },
  {
    name: 'Mattel Uno Card Game',
    img: 'https://via.placeholder.com/80x80?text=Uno',
    price: '85000',
    stock: 100,
    status: true,
    sku: 'UNO567',
  },
  {
    name: 'PlayStation DualShock 4 Controller',
    img: 'https://via.placeholder.com/80x80?text=DualShock',
    price: '650000',
    stock: 15,
    status: true,
    sku: 'PS4DS4',
  },
  {
    name: 'Xiaomi Mi Smart Band 6',
    img: 'https://via.placeholder.com/80x80?text=Mi+Band+6',
    price: '550000',
    stock: 20,
    status: false,
    sku: 'MB6600',
  },
  {
    name: 'Razer DeathAdder V2 Gaming Mouse',
    img: 'https://via.placeholder.com/80x80?text=Razer+Mouse',
    price: '1200000',
    stock: 10,
    status: false,
    sku: 'RAZV2',
  },
  {
    name: 'Samsung Galaxy Buds 2',
    img: 'https://via.placeholder.com/80x80?text=Galaxy+Buds',
    price: '1700000',
    stock: 8,
    status: false,
    sku: 'SGB2023',
  },
]
